### ISSUE TITLE
Problem following Howto

### ISSUE THREAD

**Issue by feldspar9** [ankicommunity/docker-anki-sync-server#14]
Hi,

I am trying to follow the instructions here: https://ankicommunity.github.io/Tutorials/Docker/Howto/

I have set up the docker, confirmed using the hello world command as per here https://ankicommunity.github.io/Tutorials/Docker/Howto/

Now I am trying to run this command 

docker run -it \
       --mount type=bind,source="$PERSISTENCE_DIR",target=/app/data \
       -p 27701:27701 \
       --name anki-container \
       --rm \
       $DOCKER_IMAGE

I have substituted: "$DOCKER_IMAGE" with "kuklinistvan/anki-sync-server:latest"
I have substitute: "$PERSISTENCE_DIR" with /home/aa/anki-sync-server-persistence
Where aa is my username/login
and anki-sync-server-persistence is the folder in my home location which I made using new folder

This leaves me with

docker run -it \
       --mount type=bind,source="/home/aa/anki-sync-server-persistence",target=/app/data \
       -p 27701:27701 \
       --name anki-container \
       --rm \
       kuklinistvan/anki-sync-server:latest

**However, I keep getting the following error:**

docker run -it \
>        --mount type=bind,source="/home/aa/anki-sync-server-persistence/
> ",target=/app/data \
>
invalid argument "type=bind,source=/home/aa/anki-sync-server-persistence/\n,target=/app/data" for "--mount" flag: target is required
See 'docker run --help'.

I know there must be something wrong with the code I have entered. I have tried it with and without the $ signs. 

Please note this is my first time doing something like this so please don't exclude basic obvious things to you are the reason why its not working, because they may not be apparent to me and that could be the issue. 

Thank you!

**Comment by kuklinistvan** [comment]
Hey there!

Sorry for the late response.

If my interpretation is correct, you have executed this:

```
docker run -it
--mount type=bind,source="/home/aa/anki-sync-server-persistence",target=/app/data
-p 27701:27701
--name anki-container
--rm
kuklinistvan/anki-sync-server:latest
```

...which is missing the back slashes, that indicate that the command is not over yet. It should look like this instead:

```
docker run -it \
--mount type=bind,source="/home/aa/anki-sync-server-persistence",target=/app/data \
-p 27701:27701 \
--name anki-container \
--rm \
kuklinistvan/anki-sync-server:latest
```

In the first case, every line is being interpreted as a separate command.

I hope this fixes your problem, however, **I highly encourage you to learn about shell usage first!** ([you may start here](https://ubuntu.com/tutorials/command-line-for-beginners#1-overview)) I'm affraid you will run into similar problems quite soon otherwise. Also, read some articles on how Docker, Linux, etc. works if you haven't done your research already. I'm sure it will save you same spare hours ;) 


Good luck!
